import type { LucideIcon } from "lucide-react";
import {
  AppWindowMac,
  Archive,
  ArrowDownToLine,
  AudioWaveform,
  BatteryMedium,
  BookOpen,
  Braces,
  Broom,
  Calculator,
  Camera,
  Cat,
  ChartBar,
  ChevronsLeftRight,
  ClipboardList,
  Columns2,
  Cpu,
  Database,
  Film,
  Gem,
  Globe,
  Hammer,
  ImageDown,
  Layers,
  LayoutGrid,
  Library,
  ListFilter,
  ListTree,
  Mouse,
  Network,
  Orbit,
  Package,
  Play,
  Rocket,
  Scissors,
  Search,
  SquarePen,
  SunDim,
  SunMoon,
  Telescope,
  Terminal,
  Touchpad,
  Volume2,
} from "lucide-react";
import type { IconType } from "react-icons";
import {
  Si1Password,
  SiAlfred,
  SiAnki,
  SiAnytype,
  SiArc,
  SiAudacity,
  SiBitwarden,
  SiBlender,
  SiBrave,
  SiClaude,
  SiCursor,
  SiDbeaver,
  SiDiscord,
  SiDocker,
  SiDropbox,
  SiFfmpeg,
  SiFigma,
  SiFirefoxbrowser,
  SiGhostty,
  SiGimp,
  SiGit,
  SiGithub,
  SiGooglechrome,
  SiGoogledrive,
  SiInkscape,
  SiIterm2,
  SiKeepassxc,
  SiKrita,
  SiLibreoffice,
  SiLinear,
  SiLogseq,
  SiMullvad,
  SiNeovim,
  SiNodedotjs,
  SiNotion,
  SiObsidian,
  SiObsstudio,
  SiOllama,
  SiPostman,
  SiProtonvpn,
  SiRaycast,
  SiSignal,
  SiSketch,
  SiSpotify,
  SiSublimetext,
  SiTelegram,
  SiThunderbird,
  SiTicktick,
  SiTodoist,
  SiTransmission,
  SiVlcmediaplayer,
  SiWarp,
  SiWhatsapp,
  SiZedindustries,
  SiZenbrowser,
  SiZoom,
} from "react-icons/si";
import { TbBrandVscode } from "react-icons/tb";
import type { BrandIcon } from "@/lib/catalog/brand-icons";
import {
  CapcutIcon,
  EdgeIcon,
  OfficeIcon,
  OnedriveIcon,
  OpenaiIcon,
  SafariIcon,
  SlackIcon,
  TeamsIcon,
} from "@/lib/catalog/brand-icons";
import type { CatalogPackage } from "@/lib/catalog/types";

type PackageGlyph = LucideIcon | IconType | BrandIcon;

const ICONS_BY_TOKEN: Record<string, PackageGlyph> = {
  // Browsers
  "google-chrome": SiGooglechrome,
  firefox: SiFirefoxbrowser,
  "brave-browser": SiBrave,
  "microsoft-edge": EdgeIcon,
  arc: SiArc,
  zen: SiZenbrowser,
  orion: Telescope,
  "safari-technology-preview": SafariIcon,
  // Communication
  slack: SlackIcon,
  discord: SiDiscord,
  zoom: SiZoom,
  "microsoft-teams": TeamsIcon,
  telegram: SiTelegram,
  whatsapp: SiWhatsapp,
  signal: SiSignal,
  thunderbird: SiThunderbird,
  // AI assistants
  chatgpt: OpenaiIcon,
  claude: SiClaude,
  "ollama-app": SiOllama,
  // Productivity
  notion: SiNotion,
  obsidian: SiObsidian,
  typora: SquarePen,
  ticktick: SiTicktick,
  "todoist-app": SiTodoist,
  todoist: SiTodoist,
  linear: SiLinear,
  raycast: SiRaycast,
  alfred: SiAlfred,
  rectangle: LayoutGrid,
  maccy: ClipboardList,
  logseq: SiLogseq,
  anytype: SiAnytype,
  // Office & study
  "microsoft-office": OfficeIcon,
  libreoffice: SiLibreoffice,
  skim: BookOpen,
  calibre: Library,
  anki: SiAnki,
  // Files & cloud
  "google-drive": SiGoogledrive,
  dropbox: SiDropbox,
  onedrive: OnedriveIcon,
  transmission: SiTransmission,
  jdownloader: ArrowDownToLine,
  // Media
  spotify: SiSpotify,
  vlc: SiVlcmediaplayer,
  iina: Play,
  audacity: SiAudacity,
  "handbrake-app": Film,
  capcut: CapcutIcon,
  obs: SiObsstudio,
  "blackhole-2ch": AudioWaveform,
  "background-music": Volume2,
  // Design
  figma: SiFigma,
  sketch: SiSketch,
  imageoptim: ImageDown,
  blender: SiBlender,
  inkscape: SiInkscape,
  gimp: SiGimp,
  krita: SiKrita,
  // Security & privacy
  "1password": Si1Password,
  bitwarden: SiBitwarden,
  keepassxc: SiKeepassxc,
  protonvpn: SiProtonvpn,
  "mullvad-vpn": SiMullvad,
  // Development
  "visual-studio-code": TbBrandVscode,
  cursor: SiCursor,
  zed: SiZedindustries,
  "sublime-text": SiSublimetext,
  iterm2: SiIterm2,
  ghostty: SiGhostty,
  warp: SiWarp,
  "docker-desktop": SiDocker,
  docker: SiDocker,
  orbstack: Orbit,
  github: SiGithub,
  postman: SiPostman,
  tableplus: Database,
  "dbeaver-community": SiDbeaver,
  proxyman: Network,
  // Command line
  git: SiGit,
  gh: SiGithub,
  node: SiNodedotjs,
  uv: Package,
  neovim: SiNeovim,
  tmux: Columns2,
  starship: Rocket,
  fzf: ListFilter,
  bat: Cat,
  eza: ListTree,
  jq: Braces,
  ripgrep: Search,
  wget: Globe,
  ffmpeg: SiFfmpeg,
  ollama: SiOllama,
  // Utilities
  "the-unarchiver": Package,
  keka: Archive,
  shottr: Camera,
  appcleaner: Broom,
  onyx: Gem,
  aldente: BatteryMedium,
  monitorcontrol: SunDim,
  "flux-app": SunMoon,
  linearmouse: Mouse,
  hammerspoon: Hammer,
  bettertouchtool: Touchpad,
  stats: ChartBar,
  hiddenbar: ChevronsLeftRight,
  flycut: Scissors,
  numi: Calculator,
  parallels: Layers,
  utm: Cpu,
};

const BRAND_COLOR: Record<string, string> = {
  "google-chrome": "#4285F4",
  firefox: "#FF7139",
  "brave-browser": "#FB542B",
  "microsoft-edge": "#0078D7",
  discord: "#5865F2",
  zoom: "#2D8CFF",
  telegram: "#26A5E4",
  whatsapp: "#25D366",
  signal: "#3A76F0",
  thunderbird: "#0A84FF",
  "microsoft-teams": "#6264A7",
  "microsoft-office": "#D83B01",
  claude: "#D97757",
  linear: "#5E6AD2",
  "visual-studio-code": "#007ACC",
  figma: "#F24E1E",
  sketch: "#F7B500",
  spotify: "#1DB954",
  vlc: "#FF8800",
  audacity: "#0000CC",
  "docker-desktop": "#2496ED",
  docker: "#2496ED",
  obsidian: "#7C3AED",
  blender: "#F5792A",
  "1password": "#1A56EC",
  bitwarden: "#175DDC",
  keepassxc: "#6CAC4D",
  protonvpn: "#6D4AFF",
  raycast: "#FF6363",
  "google-drive": "#4285F4",
  dropbox: "#0061FF",
  onedrive: "#28A8EA",
  libreoffice: "#18A303",
  git: "#F05032",
  node: "#339933",
  neovim: "#57A143",
  postman: "#FF6C37",
};

export function iconForPackage(pkg: CatalogPackage): PackageGlyph {
  return (
    ICONS_BY_TOKEN[pkg.token] ??
    (pkg.kind === "formula" ? Terminal : AppWindowMac)
  );
}

export function iconColorForPackage(pkg: CatalogPackage): string | undefined {
  return BRAND_COLOR[pkg.token];
}
