import type { LucideIcon } from "lucide-react";
import {
  AppWindowMac,
  Archive,
  ArrowDownToLine,
  AudioWaveform,
  BatteryMedium,
  BookOpen,
  Braces,
  Broom,
  Calculator,
  CalendarDays,
  Camera,
  Cat,
  ChartBar,
  ChevronsLeftRight,
  ClipboardList,
  Coffee,
  Columns2,
  Cpu,
  Database,
  FileText,
  Film,
  Gem,
  Globe,
  Hammer,
  ImageDown,
  Keyboard,
  LayoutGrid,
  Library,
  ListFilter,
  ListTree,
  Mouse,
  Network,
  Orbit,
  Package,
  Pause,
  Palette,
  Play,
  Presentation,
  Rocket,
  Scissors,
  Search,
  Shapes,
  Sheet,
  Snowflake,
  SquarePen,
  SquareStack,
  SunDim,
  SunMoon,
  Telescope,
  Terminal,
  Touchpad,
  Volume2,
  Wine,
} from "lucide-react";
import type { IconType } from "react-icons";
import {
  Si1Password,
  SiAlfred,
  SiAnki,
  SiAnytype,
  SiArc,
  SiAudacity,
  SiBattledotnet,
  SiBitwarden,
  SiBlender,
  SiBrave,
  SiClaude,
  SiCursor,
  SiDbeaver,
  SiDiscord,
  SiDocker,
  SiDropbox,
  SiEpicgames,
  SiFfmpeg,
  SiFigma,
  SiFirefoxbrowser,
  SiGhostty,
  SiGimp,
  SiGit,
  SiGithub,
  SiGogdotcom,
  SiGooglechrome,
  SiGoogledrive,
  SiGrammarly,
  SiInkscape,
  SiIterm2,
  SiKeepassxc,
  SiKrita,
  SiLibreoffice,
  SiLinear,
  SiLocalsend,
  SiLmstudio,
  SiLogseq,
  SiLoom,
  SiMalwarebytes,
  SiMullvad,
  SiNeovim,
  SiNodedotjs,
  SiNordvpn,
  SiNotion,
  SiObsidian,
  SiObsstudio,
  SiOllama,
  SiOnlyoffice,
  SiOpera,
  SiPerplexity,
  SiPlex,
  SiPostman,
  SiProton,
  SiProtondrive,
  SiProtonvpn,
  SiRaycast,
  SiRoblox,
  SiSignal,
  SiSketch,
  SiSpotify,
  SiSteam,
  SiSublimetext,
  SiTelegram,
  SiThunderbird,
  SiTicktick,
  SiTodoist,
  SiTransmission,
  SiVivaldi,
  SiVlcmediaplayer,
  SiWarp,
  SiWhatsapp,
  SiZedindustries,
  SiZenbrowser,
  SiZoom,
  SiZotero,
} from "react-icons/si";
import { TbBrandMinecraft, TbBrandVscode } from "react-icons/tb";
import type { BrandIcon } from "@/lib/catalog/brand-icons";
import {
  CapcutIcon,
  EdgeIcon,
  OfficeIcon,
  OnedriveIcon,
  OpenaiIcon,
  SafariIcon,
  SlackIcon,
  TeamsIcon,
} from "@/lib/catalog/brand-icons";
import type { CatalogPackage } from "@/lib/catalog/types";

type PackageGlyph = LucideIcon | IconType | BrandIcon;

const ICONS_BY_TOKEN: Record<string, PackageGlyph> = {
  // Browsers
  "google-chrome": SiGooglechrome,
  firefox: SiFirefoxbrowser,
  "brave-browser": SiBrave,
  "microsoft-edge": EdgeIcon,
  arc: SiArc,
  zen: SiZenbrowser,
  orion: Telescope,
  "safari-technology-preview": SafariIcon,
  opera: SiOpera,
  vivaldi: SiVivaldi,
  // Communication
  slack: SlackIcon,
  discord: SiDiscord,
  zoom: SiZoom,
  "microsoft-teams": TeamsIcon,
  telegram: SiTelegram,
  whatsapp: SiWhatsapp,
  signal: SiSignal,
  thunderbird: SiThunderbird,
  // AI assistants
  chatgpt: OpenaiIcon,
  claude: SiClaude,
  "ollama-app": SiOllama,
  perplexity: SiPerplexity,
  "lm-studio": SiLmstudio,
  // Productivity
  notion: SiNotion,
  obsidian: SiObsidian,
  typora: SquarePen,
  ticktick: SiTicktick,
  "todoist-app": SiTodoist,
  todoist: SiTodoist,
  linear: SiLinear,
  raycast: SiRaycast,
  alfred: SiAlfred,
  rectangle: LayoutGrid,
  maccy: ClipboardList,
  logseq: SiLogseq,
  anytype: SiAnytype,
  "notion-calendar": CalendarDays,
  "grammarly-desktop": SiGrammarly,
  loom: SiLoom,
  // Office & study
  "microsoft-office": OfficeIcon,
  libreoffice: SiLibreoffice,
  skim: BookOpen,
  calibre: Library,
  anki: SiAnki,
  "microsoft-word": FileText,
  "microsoft-excel": Sheet,
  "microsoft-powerpoint": Presentation,
  onlyoffice: SiOnlyoffice,
  "adobe-acrobat-reader": FileText,
  zotero: SiZotero,
  // Files & cloud
  "google-drive": SiGoogledrive,
  dropbox: SiDropbox,
  onedrive: OnedriveIcon,
  transmission: SiTransmission,
  jdownloader: ArrowDownToLine,
  "proton-drive": SiProtondrive,
  localsend: SiLocalsend,
  // Media
  spotify: SiSpotify,
  vlc: SiVlcmediaplayer,
  iina: Play,
  audacity: SiAudacity,
  "handbrake-app": Film,
  capcut: CapcutIcon,
  obs: SiObsstudio,
  "blackhole-2ch": AudioWaveform,
  "background-music": Volume2,
  plex: SiPlex,
  // Design
  figma: SiFigma,
  sketch: SiSketch,
  imageoptim: ImageDown,
  blender: SiBlender,
  inkscape: SiInkscape,
  gimp: SiGimp,
  krita: SiKrita,
  canva: Palette,
  affinity: Shapes,
  // Gaming
  steam: SiSteam,
  "epic-games": SiEpicgames,
  minecraft: TbBrandMinecraft,
  roblox: SiRoblox,
  "battle-net": SiBattledotnet,
  "gog-galaxy": SiGogdotcom,
  crossover: Wine,
  // Security & privacy
  "1password": Si1Password,
  bitwarden: SiBitwarden,
  keepassxc: SiKeepassxc,
  protonvpn: SiProtonvpn,
  "mullvad-vpn": SiMullvad,
  "proton-pass": SiProton,
  nordvpn: SiNordvpn,
  malwarebytes: SiMalwarebytes,
  // Development
  "visual-studio-code": TbBrandVscode,
  cursor: SiCursor,
  zed: SiZedindustries,
  "sublime-text": SiSublimetext,
  iterm2: SiIterm2,
  ghostty: SiGhostty,
  warp: SiWarp,
  "docker-desktop": SiDocker,
  docker: SiDocker,
  orbstack: Orbit,
  github: SiGithub,
  postman: SiPostman,
  tableplus: Database,
  "dbeaver-community": SiDbeaver,
  proxyman: Network,
  // Command line
  git: SiGit,
  gh: SiGithub,
  node: SiNodedotjs,
  uv: Package,
  neovim: SiNeovim,
  tmux: Columns2,
  starship: Rocket,
  fzf: ListFilter,
  bat: Cat,
  eza: ListTree,
  jq: Braces,
  ripgrep: Search,
  wget: Globe,
  ffmpeg: SiFfmpeg,
  ollama: SiOllama,
  // Utilities
  "the-unarchiver": Package,
  keka: Archive,
  shottr: Camera,
  appcleaner: Broom,
  onyx: Gem,
  aldente: BatteryMedium,
  monitorcontrol: SunDim,
  "flux-app": SunMoon,
  linearmouse: Mouse,
  hammerspoon: Hammer,
  bettertouchtool: Touchpad,
  stats: ChartBar,
  hiddenbar: ChevronsLeftRight,
  flycut: Scissors,
  numi: Calculator,
  parallels: Pause,
  utm: Cpu,
  "alt-tab": SquareStack,
  "jordanbaird-ice": Snowflake,
  mos: Mouse,
  "logi-options+": Keyboard,
  keepingyouawake: Coffee,
};

// Full-color logos in /public/icons, used where a brand's mark is multicolor
// or a single tint would misrepresent it (a blue-only Chrome reads as
// Chromium). Sources: homarr-labs/dashboard-icons (Apache-2.0), gilbarbara
// logos (CC0), devicon and vscode-icons (MIT). Monochrome marks stay as glyphs
// so they follow the theme. All marks are trademarks of their owners.
const LOGO_IDS = new Set<string>([
  "cask:1password",
  "cask:arc",
  "cask:audacity",
  "cask:bitwarden",
  "cask:blender",
  "cask:brave-browser",
  "cask:calibre",
  "cask:canva",
  "cask:claude",
  "cask:discord",
  "cask:docker-desktop",
  "cask:dropbox",
  "cask:epic-games",
  "cask:figma",
  "cask:firefox",
  "cask:gimp",
  "cask:google-chrome",
  "cask:google-drive",
  "cask:grammarly-desktop",
  "cask:handbrake-app",
  "cask:krita",
  "cask:loom",
  "cask:microsoft-edge",
  "cask:microsoft-excel",
  "cask:microsoft-powerpoint",
  "cask:microsoft-teams",
  "cask:microsoft-word",
  "cask:minecraft",
  "cask:mullvad-vpn",
  "cask:nordvpn",
  "cask:notion-calendar",
  "cask:obsidian",
  "cask:onedrive",
  "cask:onlyoffice",
  "cask:opera",
  "cask:perplexity",
  "cask:plex",
  "cask:postman",
  "cask:proton-drive",
  "cask:proton-pass",
  "cask:protonvpn",
  "cask:signal",
  "cask:slack",
  "cask:spotify",
  "cask:steam",
  "cask:telegram",
  "cask:thunderbird",
  "cask:todoist-app",
  "cask:transmission",
  "cask:visual-studio-code",
  "cask:vivaldi",
  "cask:whatsapp",
  "cask:zoom",
  "formula:git",
  "formula:node",
]);

const BRAND_COLOR: Record<string, string> = {
  "google-chrome": "#4285F4",
  firefox: "#FF7139",
  "brave-browser": "#FB542B",
  "microsoft-edge": "#0078D7",
  discord: "#5865F2",
  zoom: "#2D8CFF",
  telegram: "#26A5E4",
  whatsapp: "#25D366",
  signal: "#3A76F0",
  thunderbird: "#0A84FF",
  "microsoft-teams": "#6264A7",
  "microsoft-office": "#D83B01",
  claude: "#D97757",
  linear: "#5E6AD2",
  "visual-studio-code": "#007ACC",
  figma: "#F24E1E",
  sketch: "#F7B500",
  spotify: "#1DB954",
  vlc: "#FF8800",
  audacity: "#0000CC",
  "docker-desktop": "#2496ED",
  docker: "#2496ED",
  obsidian: "#7C3AED",
  blender: "#F5792A",
  "1password": "#1A56EC",
  bitwarden: "#175DDC",
  keepassxc: "#6CAC4D",
  protonvpn: "#6D4AFF",
  raycast: "#FF6363",
  "google-drive": "#4285F4",
  dropbox: "#0061FF",
  onedrive: "#28A8EA",
  libreoffice: "#18A303",
  git: "#F05032",
  node: "#339933",
  neovim: "#57A143",
  postman: "#FF6C37",
  opera: "#FF1B2D",
  vivaldi: "#EF3939",
  perplexity: "#1FB8CD",
  "grammarly-desktop": "#15C39A",
  loom: "#625DF5",
  "microsoft-word": "#2B579A",
  "microsoft-excel": "#217346",
  "microsoft-powerpoint": "#D24726",
  "adobe-acrobat-reader": "#EC1C24",
  zotero: "#CC2936",
  plex: "#EBAF00",
  canva: "#00C4CC",
  "battle-net": "#148EFF",
  "proton-drive": "#6D4AFF",
  "proton-pass": "#6D4AFF",
  nordvpn: "#4687FF",
  malwarebytes: "#0D3ECC",
  parallels: "#E61E25",
  iina: "#7A5CFF",
  ticktick: "#4772FA",
  todoist: "#E44332",
  logseq: "#85C8C8",
  anytype: "#FF6A7B",
  anki: "#80C2EE",
  "gog-galaxy": "#86328A",
  zed: "#084CCF",
  "sublime-text": "#FF9800",
  ghostty: "#3551F3",
  warp: "#01A4FF",
  ffmpeg: "#007808",
  localsend: "#008080",
};

export function iconForPackage(pkg: CatalogPackage): PackageGlyph {
  return (
    ICONS_BY_TOKEN[pkg.token] ??
    (pkg.kind === "formula" ? Terminal : AppWindowMac)
  );
}

export function logoForPackage(pkg: CatalogPackage): string | undefined {
  return LOGO_IDS.has(pkg.id) ? `/icons/${pkg.token}.svg` : undefined;
}

export function iconColorForPackage(pkg: CatalogPackage): string | undefined {
  return BRAND_COLOR[pkg.token];
}
