#!/bin/bash
# MacKit installer runner v1
# Downloads nothing after launch. Installs only Homebrew formulae and casks
# listed in a validated manifest. Does not collect telemetry.

set -u

usage() {
  cat <<'EOF'
MacKit installer

Usage:
  mackit-install.sh --manifest BASE64

The manifest is a Base64-encoded list of Homebrew tokens generated by MacKit.
This script never installs names that are not in that list.
EOF
}

fail() {
  printf 'MacKit: %s\n' "$1" >&2
  exit 1
}

log() {
  printf 'MacKit: %s\n' "$1"
}

cleanup() {
  if [ -n "${MACKIT_TMPDIR:-}" ] && [ -d "${MACKIT_TMPDIR}" ]; then
    rm -rf "${MACKIT_TMPDIR}"
  fi
}

trap cleanup EXIT INT TERM

MANIFEST_B64=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --manifest)
      if [ "$#" -lt 2 ]; then
        fail "Missing value for --manifest."
      fi
      MANIFEST_B64="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      fail "Unexpected argument: $1"
      ;;
  esac
done

if [ -z "${MANIFEST_B64}" ]; then
  usage >&2
  fail "A --manifest value is required."
fi

case "${MANIFEST_B64}" in
  *[!\ A-Za-z0-9+/=]*)
    fail "Manifest contains characters that are not valid Base64."
    ;;
esac

UNAME_S="$(uname -s)"
if [ "${UNAME_S}" != "Darwin" ]; then
  fail "MacKit only supports macOS."
fi

ARCH="$(uname -m)"
case "${ARCH}" in
  arm64|x86_64) ;;
  *)
    fail "Unsupported CPU architecture: ${ARCH}"
    ;;
esac

OS_VERSION="$(sw_vers -productVersion 2>/dev/null || true)"
OS_MAJOR="${OS_VERSION%%.*}"
if [ -z "${OS_MAJOR}" ] || [ "${OS_MAJOR}" -lt 14 ]; then
  fail "Homebrew requires macOS 14 or later. Detected: ${OS_VERSION:-unknown}"
fi

if ! /usr/bin/curl -fsI --max-time 8 https://formulae.brew.sh >/dev/null 2>&1; then
  fail "No network access to formulae.brew.sh."
fi

AVAILABLE_KB="$(/bin/df -k / | awk 'NR==2 {print $4}')"
if [ -n "${AVAILABLE_KB}" ] && [ "${AVAILABLE_KB}" -lt 512000 ]; then
  fail "Not enough free disk space. MacKit needs at least 500 MB free."
fi

MACKIT_TMPDIR="$(/usr/bin/mktemp -d -t mackit)"
MANIFEST_FILE="${MACKIT_TMPDIR}/manifest.txt"

printf '%s' "${MANIFEST_B64}" | /usr/bin/base64 -D > "${MANIFEST_FILE}" 2>/dev/null \
  || printf '%s' "${MANIFEST_B64}" | /usr/bin/base64 -d > "${MANIFEST_FILE}" \
  || fail "Could not decode the install manifest."

HEADER="$(/usr/bin/sed -n '1p' "${MANIFEST_FILE}")"
if [ "${HEADER}" != "MACKIT/1" ]; then
  fail "Unsupported MacKit manifest."
fi

FORMULAE=()
CASKS=()
COUNT=0

while IFS= read -r line || [ -n "${line}" ]; do
  [ -z "${line}" ] && continue
  [ "${line}" = "MACKIT/1" ] && continue

  kind="${line%% *}"
  token="${line#* }"

  if [ "${kind}" != "f" ] && [ "${kind}" != "c" ]; then
    fail "Invalid manifest line: ${line}"
  fi

  if [ "${token}" = "${line}" ] || [ -z "${token}" ]; then
    fail "Invalid manifest line: ${line}"
  fi

  case "${token}" in
    *[!a-z0-9+._@-]*|-*|"")
      fail "Rejected Homebrew token: ${token}"
      ;;
  esac

  COUNT=$((COUNT + 1))
  if [ "${COUNT}" -gt 50 ]; then
    fail "Manifest exceeds the 50-package limit."
  fi

  if [ "${kind}" = "f" ]; then
    FORMULAE+=("${token}")
  else
    CASKS+=("${token}")
  fi
done < "${MANIFEST_FILE}"

if [ "${COUNT}" -eq 0 ]; then
  fail "Manifest does not contain any packages."
fi

find_brew() {
  if [ -x /opt/homebrew/bin/brew ]; then
    printf '%s' /opt/homebrew/bin/brew
    return 0
  fi
  if [ -x /usr/local/bin/brew ]; then
    printf '%s' /usr/local/bin/brew
    return 0
  fi
  return 1
}

BREW="$(find_brew || true)"

if [ -z "${BREW}" ]; then
  cat <<'EOF'
Homebrew is not installed.

Homebrew is the official package manager MacKit uses to install apps and
command-line tools. Its installer will explain each step and may ask for
your Mac password.

Official installer:
https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh

EOF
  printf 'Install Homebrew now? [y/N] '
  read -r ANSWER
  case "${ANSWER}" in
    y|Y|yes|YES)
      /bin/bash -c "$(/usr/bin/curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" \
        || fail "Homebrew installation did not complete."
      BREW="$(find_brew || true)"
      if [ -z "${BREW}" ]; then
        fail "Homebrew installed, but brew was not found in /opt/homebrew or /usr/local."
      fi
      ;;
    *)
      fail "Homebrew is required. Re-run this command when you are ready."
      ;;
  esac
fi

log "Using ${BREW} on ${ARCH} macOS ${OS_VERSION}"

INSTALLED=()
SKIPPED=()
FAILED=()

already_installed() {
  local kind="$1"
  local token="$2"
  if [ "${kind}" = "formula" ]; then
    "${BREW}" list --formula --versions "${token}" >/dev/null 2>&1
  else
    "${BREW}" list --cask --versions "${token}" >/dev/null 2>&1
  fi
}

install_one() {
  local kind="$1"
  local token="$2"

  if already_installed "${kind}" "${token}"; then
    SKIPPED+=("${token}")
    log "Skipped ${token} (already installed)"
    return 0
  fi

  if [ "${kind}" = "formula" ]; then
    if "${BREW}" install --formula "${token}"; then
      INSTALLED+=("${token}")
      log "Installed ${token}"
    else
      FAILED+=("${token}")
      log "Failed ${token}"
    fi
  else
    if "${BREW}" install --cask "${token}"; then
      INSTALLED+=("${token}")
      log "Installed ${token}"
    else
      FAILED+=("${token}")
      log "Failed ${token}"
    fi
  fi
}

for token in "${FORMULAE[@]+"${FORMULAE[@]}"}"; do
  [ -z "${token}" ] && continue
  install_one formula "${token}"
done

for token in "${CASKS[@]+"${CASKS[@]}"}"; do
  [ -z "${token}" ] && continue
  install_one cask "${token}"
done

printf '\nMacKit summary\n'
printf '  Installed: %s\n' "${#INSTALLED[@]}"
printf '  Skipped:   %s\n' "${#SKIPPED[@]}"
printf '  Failed:    %s\n' "${#FAILED[@]}"

if [ "${#INSTALLED[@]}" -gt 0 ]; then
  printf '  Newly installed: %s\n' "${INSTALLED[*]}"
fi
if [ "${#SKIPPED[@]}" -gt 0 ]; then
  printf '  Already present: %s\n' "${SKIPPED[*]}"
fi
if [ "${#FAILED[@]}" -gt 0 ]; then
  printf '  Could not install: %s\n' "${FAILED[*]}"
  exit 1
fi

exit 0
